config/routes.rb
Rails.application.routes.draw do
  
  get '/doc' => 'portal#doc' 
  


  devise_for :admins, :controllers => {registrations: "admin/registrations", sessions: "admin/sessions", passwords: "admin/passwords"}, path: 'admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "admin/dashboard#index"
  authenticate :admin do
    namespace :admin do
      get '/' => 'dashboard#index'
     
      get '/setting' => 'dashboard#edit'
      post '/setting' => 'dashboard#update'
      
      resources :employees, only: [:index, :new, :create, :edit, :update, :destroy] do
        member do
          patch 'update_status' => 'users#update_status'
        end
      end
      
      resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :permissions, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :apps, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :service_zones, only: [:index, :edit, :update, :destroy]
        member do
          patch 'remove_screenshot' => 'apps#remove_screenshot'
          delete 'clean_service_zones' => 'apps#clean_service_zones'
          patch 'update_checkin' => 'apps#update_checkin'
        end
      end

      resources :salesmen, only: [:index, :new, :create, :edit, :update]

      resources :tasks, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
        resources :distributes, only: [:index] do
          collection do
            patch 'update_task' => 'distributes#update_task'
          end
        end
        resources :task_amounts, only: [:index] do
          collection do
            patch 'update_amount' => 'task_amounts#update_amount'
          end
        end
      end
      resources :channels, only: [:index, :new, :create, :edit, :update, :destroy] do
        # resources :templates, only: [:index, :new, :create, :show, :edit, :update, :destroy], controller: 'channel_templates' do
        #   member do
        #     post '/update_params' => 'channel_templates#update_params'
        #   end
        #   collection do
        #     get '/selection' => 'channel_templates#selection'
        #   end
        # end
      end

      resources :reports, only: [] do
        collection do
          get '/channel' => 'reports#channel'
          get '/user' => 'reports#user'
          get '/agency' => 'reports#agency'
          get '/channel_exposures' => 'reports#channel_exposures'
          get '/agency_exposures' => 'reports#agency_exposures'
          
          # get '/click_log' => 'reports#click_log'
          # get '/notify_log' => 'reports#notify_log'
        end
      end
      resources :agencies, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :channel_exposures, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :agencies_exposure, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :inserts,only:[:index,:new,:create]  do
        collection do
          get '/create_data' => 'inserts#create_data'
        end
      end
      resources :imports,only:[:index,:new,:create]  do
      
      end

      
    end
  end
end

app/models/permission.rb
class Permission < ApplicationRecord
	 has_and_belongs_to_many :roles, :join_table => :role_permissions
  # accepts_nested_attributes_for :roles

  # tree structure
  acts_as_tree cache_depth: true
  
  validates :resource_name, presence: true
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::ApplicationController
  layout 'admin/layouts/application'
  
  before_action :find_permission, only:[:edit, :update, :destroy]

  def index
    @ancestry_options = Permission.where("ancestry is null").order("id asc").pluck(:name, :id).unshift(["请选择", nil])
    @q = Permission.search(params[:q])
    @permissions = @q.result.order("ancestry desc, created_at desc").paginate(:page => params[:page])
  end

  def new
  	@permission = Permission.new
  end

  def create
    # @permission = Permission.new(permission_params)
    # if @permission.save
    #   redirect_to admin_permissions_path, notice: "添加成功！"
    # else
    #   render 'new'
    # end
  end

  def edit
  	
  end

  def update
    if @permission.update(permission_params)
      redirect_to admin_permissions_path, notice: "修改成功！"
    else
      render 'edit'
    end
  end
  
  def destroy
    # @permission.destroy
    # redirect_to admin_permissions_path, notice: "删除成功！"
  end


  private
  def find_permission
    @permission = Permission.find(params[:id])
    rescue => e
      redirect_to admin_permissions_path, alert: '没有找到数据'
  end
  
  def permission_params
    params.require(:permission).permit(:name)
  end
  
end

app/views/admin/permissions/_form.html.erb
<%= render 'admin/shared/error_messages', object: f.object %>

<%= f.input :name, input_html: {class:'form-control'} %>

<% if ['edit', 'update'].include? action_name %>
	<label>所属资源</label>
	<input type="text" disabled value="<%= f.object.parent.present? ? f.object.parent.name : f.object.name %>" class="form-control">
<% end %>
<%= f.input :resource_name, input_html: {class:'form-control', disabled: "disabled"} %>

app/views/admin/permissions/edit.html.erb
<% provide(:title, '修改权限') %>

<h1 class="page-header">修改权限</h1>

<div class="bs-example">
<%= simple_form_for @permission, url: admin_permission_path(@permission), method: :patch, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '修改权限', :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>

app/views/admin/permissions/index.html.erb
<% provide(:title, "权限列表") %>
<h1 class="page-header">权限列表</h1>

<div class="well form-inline" style="margin-top:20px">
  <%= search_form_for @q, url: admin_permissions_path do |f| %>
    <%= f.label :name_cont, '权限名称' %>
    <%= f.search_field :name_cont, class:'form-control' %> 
    <%= f.label :resource_name_cont, '资源名称' %>
    <%= f.search_field :resource_name_cont, class:'form-control' %> 
    <%= f.label :ancestry_eq, '所属资源' %>
    <%= f.select :ancestry_eq, @ancestry_options, {}, class:'form-control' %>
    <%= f.submit('搜索', class:'btn btn-success') %>
  <% end %>
</div>

<div class="span9">
  <% if @permissions.any? %>
    <%= will_paginate %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th width="20%">权限名称</th>
          <th width="30%">所属资源</th>
          <th width="30%">资源名称</th>
          <th width="20%">操作</th>
        </tr>
      </thead>
      <tbody>
        <% @permissions.each do |permission| %>
        <tr>
          <td><%= permission.name %></td>
          <td><%= permission.parent.present? ? permission.parent.name : permission.name %></td>
          <td><%= permission.resource_name %></td>
          <td>
            <%= link_to '修改', edit_admin_permission_path(permission), class: 'btn btn-success' %>
            <!-- <%= link_to '删除', admin_permission_path(permission), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %> -->
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  <% end %>
</div>

app/views/admin/permissions/new.html.erb
<% provide(:title, '新增权限') %>

<h1 class="page-header">新增权限</h1>

<div class="bs-example">
<%= simple_form_for @permission, url: admin_permissions_path, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '新增权限', :class => 'btn btn-success' %>
<% end %>
</div>