config/routes.rb
Rails.application.routes.draw do
  
  get '/doc' => 'portal#doc' 
  


  devise_for :admins, :controllers => {registrations: "admin/registrations", sessions: "admin/sessions", passwords: "admin/passwords"}, path: 'admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "admin/dashboard#index"
  authenticate :admin do
    namespace :admin do
      get '/' => 'dashboard#index'
     
      get '/setting' => 'dashboard#edit'
      post '/setting' => 'dashboard#update'
      
      resources :employees, only: [:index, :new, :create, :edit, :update, :destroy] do
        member do
          patch 'update_status' => 'users#update_status'
        end
      end
      
      resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :permissions, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :apps, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :service_zones, only: [:index, :edit, :update, :destroy]
        member do
          patch 'remove_screenshot' => 'apps#remove_screenshot'
          delete 'clean_service_zones' => 'apps#clean_service_zones'
          patch 'update_checkin' => 'apps#update_checkin'
        end
      end

      resources :salesmen, only: [:index, :new, :create, :edit, :update]

      resources :tasks, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
        resources :distributes, only: [:index] do
          collection do
            patch 'update_task' => 'distributes#update_task'
          end
        end
        resources :task_amounts, only: [:index] do
          collection do
            patch 'update_amount' => 'task_amounts#update_amount'
          end
        end
      end
      resources :channels, only: [:index, :new, :create, :edit, :update, :destroy] do
        # resources :templates, only: [:index, :new, :create, :show, :edit, :update, :destroy], controller: 'channel_templates' do
        #   member do
        #     post '/update_params' => 'channel_templates#update_params'
        #   end
        #   collection do
        #     get '/selection' => 'channel_templates#selection'
        #   end
        # end
      end

      resources :reports, only: [] do
        collection do
          get '/channel' => 'reports#channel'
          get '/user' => 'reports#user'
          get '/agency' => 'reports#agency'
          get '/channel_exposures' => 'reports#channel_exposures'
          get '/agency_exposures' => 'reports#agency_exposures'
          
          # get '/click_log' => 'reports#click_log'
          # get '/notify_log' => 'reports#notify_log'
        end
      end
      resources :agencies, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :channel_exposures, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :agencies_exposure, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :inserts,only:[:index,:new,:create]  do
        collection do
          get '/create_data' => 'inserts#create_data'
        end
      end
      resources :imports,only:[:index,:new,:create]  do
      
      end

      
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :permissions, :join_table => :role_permissions
  accepts_nested_attributes_for :permissions
  
  has_and_belongs_to_many :admins, :join_table => :admin_roles
  accepts_nested_attributes_for :admins
  
  validates :name, presence: true
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::ApplicationController
  layout 'admin/layouts/application'
  
  before_action :find_admin, only:[:edit, :update, :update_status, :destroy]
  before_action :find_roles, only:[:new, :create, :edit, :update]

  def index
    @admins = Admin.includes(:roles).all
  end
  
  def new
    @admin = Admin.new
  end

  def edit
    @role_ids = @admin.role_ids
  end
  
  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      if params[:role_ids].present?
        params[:role_ids].each do |id|
          role = Role.find_by_id(id)
          @admin.roles << role
        end
      end
      redirect_to admin_employees_path, notice: "添加成功！"
    else
      render 'new'
    end
  end
  
  def update
    if @admin.id != 1 || current_admin.id == 1
      update_params = params.require(:admin).permit(:password) 
      if @admin.update(update_params)
        if params[:role_ids].present?
          param_ids = params[:role_ids].map {|id| id.to_i}
          role_ids = @admin.role_ids
          remove_ids = role_ids - param_ids
          param_ids.each do |id|
            role = Role.find_by_id(id)
            @admin.roles << role unless @admin.roles.exists?(role)
          end
          remove_ids.each do |id|
            role = Role.find_by_id(id)
            @admin.roles.destroy(role)
          end
        else
          @admin.roles.clear
        end
        redirect_to admin_employees_path, notice: "修改成功！"
      else
        render 'edit'
      end
    else
      redirect_to admin_employees_path, :alert => 'id 1 管理员不能修改'
    end
  end
  
  def destroy
    if @admin.id == 1
      redirect_to admin_employees_path, :alert => 'id 1 管理员不能删除'
    else
      @admin.destroy
      redirect_to admin_employees_path, notice: "删除成功！"
    end    
  end
  
  private
  def find_admin
    @admin = Admin.find(params[:id])
    rescue => e
      redirect_to admin_employees_path, alert: '没有找到数据'
  end
  
  def find_roles
    @roles = Role.all
  end

  def admin_params
    params.require(:admin).permit(:username, :email, :password)
  end

end

app/views/admin/employees/_form.html.erb
<%= render 'admin/shared/error_messages', object: f.object %>

<% if ['edit', 'update'].include? action_name %>
<%= f.input :email, disabled: true, input_html: {class:'form-control'} %>
<% else %>
<%= f.input :email, input_html: {class:'form-control'} %>
<% end %>

<% if ['edit', 'update'].include? action_name %>
<%= f.input :username, disabled: true, input_html: {class:'form-control'} %>
<% else %>
<%= f.input :username, input_html: {class:'form-control'} %>
<% end %>

<%= f.input :password, input_html: {class:'form-control'} %>

<% if roles.present? %>
<label>管理员角色</label>
<div class="well">
<%
if params[:role_ids].present? 
  ids = params[:role_ids].map {|id| id.to_i}
elsif @role_ids.present?
	ids = @role_ids.map {|id| id.to_i}
end 
%>

<% roles.each do |role| %>
	<label>
		<input type="checkbox" name=role_ids[] value="<%= role.id %>" <%= "checked" if ids.present? && ids.include?(role.id) %>> <%= role.name %>
	</label>
<% end %>
</div>
<% end %>

app/views/admin/employees/edit.html.erb
<% provide(:title, '修改管理员') %>

<h1 class="page-header">修改管理员</h1>

<div class="bs-example">
<%= simple_form_for @admin, url: admin_employee_path(@admin), method: :patch, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f, :roles => @roles, :permission_ids => @permission_ids } %>
  <%= f.submit '修改管理员', :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>

app/views/admin/employees/index.html.erb
<% provide(:title, "管理员列表") %>
<h1 class="page-header">管理员列表</h1>

<div class="table-responsive">
  <%= link_to '新增管理员', new_admin_employee_path, class: 'btn btn-success' %>
</div>

<div class="span9">
  <% if @admins.any? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th width="20%">用户名</th>
          <th width="30%">邮箱</th>
          <th width="30%">管理员角色</th>
          <th width="20%">操作</th>
        </tr>
      </thead>
      <tbody>
        <% @admins.each do |admin| %>
        <tr>
          <td><%= admin.username %></td>
          <td><%= admin.email %></td>
          <td> 
            <% if admin.id == 1 %>
              超级管理员
            <% else %>
              <% admin.roles.each do |role| %>
                <%= role.name + " " %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to '修改', edit_admin_employee_path(admin), class: 'btn btn-success' %>
            <%= link_to '删除', admin_employee_path(admin), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/admin/employees/new.html.erb
<% provide(:title, '新增管理员') %>

<h1 class="page-header">新增管理员</h1>

<div class="bs-example">
<%= simple_form_for @admin, url: admin_employees_path, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f, :roles => @roles } %>
  <%= f.submit '新增管理员', :class => 'btn btn-success' %>
<% end %>
</div>