config/routes.rb
Rails.application.routes.draw do
  
  get '/doc' => 'portal#doc' 
  


  devise_for :admins, :controllers => {registrations: "admin/registrations", sessions: "admin/sessions", passwords: "admin/passwords"}, path: 'admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "admin/dashboard#index"
  authenticate :admin do
    namespace :admin do
      get '/' => 'dashboard#index'
     
      get '/setting' => 'dashboard#edit'
      post '/setting' => 'dashboard#update'
      
      resources :employees, only: [:index, :new, :create, :edit, :update, :destroy] do
        member do
          patch 'update_status' => 'users#update_status'
        end
      end
      
      resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :permissions, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :apps, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :service_zones, only: [:index, :edit, :update, :destroy]
        member do
          patch 'remove_screenshot' => 'apps#remove_screenshot'
          delete 'clean_service_zones' => 'apps#clean_service_zones'
          patch 'update_checkin' => 'apps#update_checkin'
        end
      end

      resources :salesmen, only: [:index, :new, :create, :edit, :update]

      resources :tasks, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
        resources :distributes, only: [:index] do
          collection do
            patch 'update_task' => 'distributes#update_task'
          end
        end
        resources :task_amounts, only: [:index] do
          collection do
            patch 'update_amount' => 'task_amounts#update_amount'
          end
        end
      end
      resources :channels, only: [:index, :new, :create, :edit, :update, :destroy] do
        # resources :templates, only: [:index, :new, :create, :show, :edit, :update, :destroy], controller: 'channel_templates' do
        #   member do
        #     post '/update_params' => 'channel_templates#update_params'
        #   end
        #   collection do
        #     get '/selection' => 'channel_templates#selection'
        #   end
        # end
      end

      resources :reports, only: [] do
        collection do
          get '/channel' => 'reports#channel'
          get '/user' => 'reports#user'
          get '/agency' => 'reports#agency'
          get '/channel_exposures' => 'reports#channel_exposures'
          get '/agency_exposures' => 'reports#agency_exposures'
          
          # get '/click_log' => 'reports#click_log'
          # get '/notify_log' => 'reports#notify_log'
        end
      end
      resources :agencies, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :channel_exposures, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :agencies_exposure, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :inserts,only:[:index,:new,:create]  do
        collection do
          get '/create_data' => 'inserts#create_data'
        end
      end
      resources :imports,only:[:index,:new,:create]  do
      
      end

      
    end
  end
end

app/models/agency.rb
class Agency < ApplicationRecord
	has_many :agency_tasks
	has_many :user_tasks

	validates :name, presence: true, uniqueness: true
	before_validation :auto_fill, on: :create

	protected
	def auto_fill
		if self.name.present?
			pinyin = ::PinYin.of_string(self.name, :ascii)
			self.letter = pinyin[0][0].upcase
			self.key = SecureRandom.urlsafe_base64
			
		end
	end
end

app/controllers/admin/agencies_controller.rb
require 'admin/application_controller'
class Admin::AgenciesController < Admin::ApplicationController
  layout 'admin/layouts/application'
  
  before_filter :find_agency, only:[:edit, :update, :destroy]
  
  def index
    
    @q = Agency.search(params[:q])
    @agencies = @q.result.paginate(:page => params[:page])
  end
  
  def new
    @agency = Agency.new
  end

  def edit
    
  end
  
  def create
    @agency = Agency.new(agency_params)
    
    if @agency.save
      flash[:success] = "添加成功！"
      redirect_to admin_agencies_path
    else
      render 'new'
    end
  end
  
  def update
    if @agency.update(agency_params)
      flash[:success] = "修改成功！"
      redirect_to admin_agencies_path
    else
      render 'edit'
    end
  end
  
  def destroy
    if @agency.agency_tasks.any?
      redirect_to admin_agencies_path, :alert => '已有接入任务，无法删除'
    else
      @agency.destroy
      redirect_to admin_agencies_path, notice: "删除成功！"
    end
  end
  
  private
  def find_agency
    @agency = Agency.find(params[:id])
    rescue Exception => exception
      redirect_to admin_agencies_path, alert: '没有找到数据'
  end
  
  def agency_params
    params.require(:agency).permit(:name, :intro)
  end
end

app/views/admin/agencies/_form.html.erb
<%= render 'admin/shared/error_messages', object: f.object %>

<%= f.input :name, input_html: {class:'form-control'} %>

<%= f.input :intro, as: :text, input_html: {class:'form-control'} %>

app/views/admin/agencies/edit.html.erb
<% provide(:title, '修改渠道') %>
<h1 class="page-header">修改渠道</h1>

<div class="bs-example">
<%= simple_form_for @agency, url: admin_agency_path(@agency), method: :patch, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '修改渠道', :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>

app/views/admin/agencies/index.html.erb
<% provide(:title, "渠道列表") %>
<h1 class="page-header">渠道列表</h1>

<div class="table-responsive">
  <%= link_to '新增渠道', new_admin_agency_path, class: 'btn btn-success' %>
</div>

<div class="well form-inline" style="margin-top:20px">
  <%= search_form_for @q, url: admin_agencies_path do |f| %>
    <%= f.label :name_cont, '渠道名称' %>
    <%= f.search_field :name_cont, class:'form-control' %> 
    <%= f.submit('搜索', class:'btn btn-success') %>
  <% end %>
</div>

<div class="span9">
  <% if @agencies.any? %>
    <%= will_paginate %>
    <table class="table table-hover">
      <caption></caption>
      <thead>
        <tr>
          <th>渠道名称</th>
          <th>渠道介绍</th>
          <th>密钥</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% @agencies.each do |agency| %>
        <tr>
          <td><%= agency.name %></td>
          <td><%= agency.intro %></td>
          <td><%= agency.key %></td>
          <td>
            <%= link_to '修改', edit_admin_agency_path(agency), class: 'btn btn-success' %>
            <%= link_to '删除', admin_agency_path(agency), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  <% end %>
</div>

app/views/admin/agencies/new.html.erb
<% provide(:title, '新增渠道') %>
<h1 class="page-header">新增渠道</h1>

<div class="bs-example">
<%= simple_form_for @agency, url: admin_agencies_path, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '新增渠道', :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>