config/routes.rb
Rails.application.routes.draw do
  
  get '/doc' => 'portal#doc' 
  


  devise_for :admins, :controllers => {registrations: "admin/registrations", sessions: "admin/sessions", passwords: "admin/passwords"}, path: 'admin'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "admin/dashboard#index"
  authenticate :admin do
    namespace :admin do
      get '/' => 'dashboard#index'
     
      get '/setting' => 'dashboard#edit'
      post '/setting' => 'dashboard#update'
      
      resources :employees, only: [:index, :new, :create, :edit, :update, :destroy] do
        member do
          patch 'update_status' => 'users#update_status'
        end
      end
      
      resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :permissions, only: [:index, :new, :create, :show, :edit, :update, :destroy]
      resources :apps, only: [:index, :new, :create, :edit, :update, :destroy] do
        resources :service_zones, only: [:index, :edit, :update, :destroy]
        member do
          patch 'remove_screenshot' => 'apps#remove_screenshot'
          delete 'clean_service_zones' => 'apps#clean_service_zones'
          patch 'update_checkin' => 'apps#update_checkin'
        end
      end

      resources :salesmen, only: [:index, :new, :create, :edit, :update]

      resources :tasks, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
        resources :distributes, only: [:index] do
          collection do
            patch 'update_task' => 'distributes#update_task'
          end
        end
        resources :task_amounts, only: [:index] do
          collection do
            patch 'update_amount' => 'task_amounts#update_amount'
          end
        end
      end
      resources :channels, only: [:index, :new, :create, :edit, :update, :destroy] do
        # resources :templates, only: [:index, :new, :create, :show, :edit, :update, :destroy], controller: 'channel_templates' do
        #   member do
        #     post '/update_params' => 'channel_templates#update_params'
        #   end
        #   collection do
        #     get '/selection' => 'channel_templates#selection'
        #   end
        # end
      end

      resources :reports, only: [] do
        collection do
          get '/channel' => 'reports#channel'
          get '/user' => 'reports#user'
          get '/agency' => 'reports#agency'
          get '/channel_exposures' => 'reports#channel_exposures'
          get '/agency_exposures' => 'reports#agency_exposures'
          
          # get '/click_log' => 'reports#click_log'
          # get '/notify_log' => 'reports#notify_log'
        end
      end
      resources :agencies, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :channel_exposures, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :agencies_exposure, only: [:index, :new, :create, :edit, :update, :destroy] do
      end
      resources :inserts,only:[:index,:new,:create]  do
        collection do
          get '/create_data' => 'inserts#create_data'
        end
      end
      resources :imports,only:[:index,:new,:create]  do
      
      end

      
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
	has_and_belongs_to_many :permissions, :join_table => :role_permissions
  accepts_nested_attributes_for :permissions
  
  has_and_belongs_to_many :admins, :join_table => :admin_roles
  accepts_nested_attributes_for :admins
  
  validates :name, presence: true
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::ApplicationController
  layout 'admin/layouts/application'
  before_action :find_role, only:[:edit, :update, :destroy]
  before_action :find_permissions, only: [:new, :create, :edit, :update]

  def index
  	@roles = Role.includes(:admins, :permissions).all
  end

  def new
  	@role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
    	if params[:ids].present?
        params[:ids].each do |id|
          permission = Permission.find_by_id(id)
          @role.permissions << permission
        end
      end
      redirect_to admin_roles_path, notice: "添加成功！"
    else
      render 'new'
    end
  end

  def edit
  	@permission_ids = @role.permission_ids
  end

  def update
    if @role.update(role_params)
    	if params[:ids].present?
        param_ids = params[:ids].map {|id| id.to_i}
        permission_ids = @role.permission_ids
        remove_ids = permission_ids - param_ids
        param_ids.each do |id|
          permission = Permission.find_by_id(id)
          @role.permissions << permission unless @role.permissions.exists?(permission)
        end
        remove_ids.each do |id|
          permission = Permission.find_by_id(id)
          @role.permissions.destroy(permission)
        end
      else
      	@role.permissions.clear
      end
      redirect_to admin_roles_path, notice: "修改成功！"
    else
      render 'edit'
    end
  end
  
  def destroy
		if @role.admins.present?
			redirect_to admin_roles_path, alert: "该角色已关联管理员，无法删除！"
		else
			@role.destroy
	  	redirect_to admin_roles_path, notice: "删除成功！"
		end
  end



  private
  def find_role
    @role = Role.find(params[:id])
    rescue => e
      redirect_to admin_roles_path, alert: '没有找到数据'
  end
  
  def find_permissions
  	@permissions = []
  	permissions = Permission.where("ancestry is NULL")
  	permissions.each do |permission|
  		p = {}
  		p["controller"] = [permission.id, permission.name]
  		permission_id_and_name = permission.children.pluck(:id, :name)
  		p["action"] = permission_id_and_name
  		@permissions << p
  	end
  end

  def role_params
    params.require(:role).permit(:name, permissions_attributes: [:id, :name, :resource_name])
  end
  
end

app/views/admin/roles/_form.html.erb
<%= render 'admin/shared/error_messages', object: f.object %>

<%= f.input :name, input_html: {class:'form-control'} %>
<label>角色权限</label>
<div class="well">
<%  
if params[:ids].present? 
  ids = params[:ids].map {|id| id.to_i}
elsif permission_ids.present?
	ids = permission_ids.map {|id| id.to_i}
end 
%>
	<% permissions.each_with_index do |permission, index| %>
		<div id="permission_<%= index %>">
			<label class="group_controller">
				<input type="checkbox" id="group_<%= index %>"  name="ids[]" value="<%= permission['controller'][0] %>" <%= "checked" if (ids.present? && ids.include?(permission['controller'][0])) %>> <%= permission["controller"][1] %>
			</label>
			<% permission['action'].each do |action| %>
				<label>
					<input type="checkbox" class="group_<%= index %>" name="ids[]" value="<%= action[0] %>" <%= "checked" if (ids.present? && ids.include?(action[0])) %>> <%= action[1] %>
				</label>
			<% end %>
		</div>
	<% end %>
</div>

<script>
$(document).ready(function() {
	$(".group_controller").each(function(index, el) {
		$(this).click(function(event) {
			var input = $(this).children("input");
			var name = input.attr("id");
			if (input.is(":checked")) {
				// if (!$("." + name + ":checked")) {
					$("." + name).each(function(index, el) {
						$(this).prop("checked", true);
					});
				// };
			} else {
				$("." + name).each(function(index, el) {
					$(this).prop("checked", false);
				});
			}
		});
	});
});
</script>

app/views/admin/roles/edit.html.erb
<% provide(:title, '修改角色') %>

<h1 class="page-header">修改角色</h1>

<div class="bs-example">
<%= simple_form_for @role, url: admin_role_path(@role), method: :patch, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f, :permissions => @permissions, :permission_ids => @permission_ids } %>
  <%= f.submit '修改角色', :class => 'btn btn-success', 'data-disable-with' => '提交中...' %>
<% end %>
</div>

app/views/admin/roles/index.html.erb
<% provide(:title, "角色列表") %>
<h1 class="page-header">角色列表</h1>

<div class="table-responsive">
  <%= link_to '新增角色', new_admin_role_path, class: 'btn btn-success' %>
</div>

<div class="span9">
  <% if @roles.any? %>
    <table class="table table-hover">
      <thead>
        <tr>
          <th width="30%">角色名称</th>
          <th width="30%">角色权限</th>
          <th width="20%">已关联管理员</th>
          <th width="20%">操作</th>
        </tr>
      </thead>
      <tbody>
        <% @roles.each do |role| %>
        <tr>
          <td><%= role.name %></td>
          <td>
            <% role.permissions.each do |permission| %>
              <%= permission.name + " " %>
            <% end %>
          </td>
          <td><%= role.admins.present? ? "是" : "否" %></td> 
          <td>
            <%= link_to '修改', edit_admin_role_path(role), class: 'btn btn-success' %>
            <%= link_to '删除', admin_role_path(role), class: 'btn btn-danger', data:{confirm: '确定删除吗?'}, method: :delete %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/admin/roles/new.html.erb
<% provide(:title, '新增角色') %>

<h1 class="page-header">新增角色</h1>
<div class="bs-example">
<%= simple_form_for @role, url: admin_roles_path, html: {class: 'form'} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f, :permissions => @permissions, :permission_ids => @permission_ids } %>
  <%= f.submit '新增角色', :class => 'btn btn-success' %>
<% end %>
</div>